### ISSUE TITLE
Typo in tutorial "Lévy Flight"

### ISSUE THREAD

**Issue by melissawm** [knaidoo29/mistree#10]
In https://knaidoo29.github.io/mistreedoc/levy_flight.html there is a typo:
```
We plot the 3 dimensions across 3 plains: X vs Y, X vs Z and Z vs Y:
```
should read 
```
We plot the 3 dimensions across 3 planes: X vs Y, X vs Z and Z vs Y:
```

**Comment by knaidoo29** [comment]
Thanks, I've corrected this in the documentation and in the tutorial notebooks.
