### ISSUE TITLE
Include instructions for how to run tests

### ISSUE THREAD

**Issue by melissawm** [knaidoo29/mistree#11]
This might be important for new users.

**Comment by knaidoo29** [comment]
So I'm not sure how you would run test on the pip install (maybe you have a suggestion?) but if you download 

`git clone https://github.com/knaidoo29/mistree.git`
`cd mistree`

Then run (which requires nose):

`python setup.py test`

or (which uses pytest)

`pytest`

I can include this in the documentation.

**Comment by knaidoo29** [comment]
correction: the last command should be

`python -m pytest`

it might not recognise pytest otherwise.

**Comment by knaidoo29** [comment]
Note, I've added this to the documentation and the README doc.

**Comment by melissawm** [comment]
Great, thanks!
