### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by raul-bermejo** [knaidoo29/mistree#13]
Hi, I'm trying to install mistree using pip and I get the following error:

  building 'mistree.levy_flight.utility_random_walk' extension
  error: extension 'mistree.levy_flight.utility_random_walk' has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for mistree

Is there any fortran requirement? I could not see anything in the Dependencies.
I also tried to clean my environment but still get the same issue.

Cheers,
Raul

**Comment by knaidoo29** [comment]
Hi Raul,

There are some fortran subroutines which need to be built on your machine. Try installing a fortran compiler using:

sudo apt-get install gfortran

Or by installing gcc, see the install instructions [here](https://gcc.gnu.org/install/). If you're using anaconda you can follow the instructions [here](https://anaconda.org/conda-forge/gcc).

And then try reinstalling using pip. I will add a comment about this in the documentation.

Let me know if that works.

Best,

Krishna

**Comment by raul-bermejo** [comment]
Hi Krishna,

Thank you very much. Installing gcc worked.
I am not able to install it on windows but I will open a new issue. I will close this now.

Thanks,
Raul
