### ISSUE TITLE
np.bool is deprecated in python 3.8

### ISSUE THREAD

**Issue by meyerls** [knaidoo29/mistree#18]
Hi @knaidoo29!

thanks for your amazing work! Unfortunately in python 3.8 np.bool does not exist anymore.

In [branes.py](https://github.com/knaidoo29/mistree/blob/master/mistree/mst/branches.py) in lines 54 and 55  ```np.bool``` occurs twice.

```python 
mask_end = np.ones(index_branch_end.shape, dtype=np.bool)
mask_mid = np.ones(index_branch_mid.shape, dtype=np.bool)
```

Could you please replace it with ```bool``` or ```np.bool_```? 

Otherwise, I could push my current branch.

**Comment by knaidoo29** [comment]
Hi @meyerls , I'm aware of this problem. Just haven't gotten around to fixing it. I will do it today. So now worries but thanks!

**Comment by knaidoo29** [comment]
This error has now been fixed in the latest version, and available in an update to the pip version.

**Comment by meyerls** [comment]
Wow, amazing! Thanks
