### ISSUE TITLE
ValueError in “get_branch_index” function

### ISSUE THREAD

**Issue by eunheeko** [knaidoo29/mistree#21]
Hello,

I get the following error message.

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.`

It seems '_twig' in `get_branch_index` appends an numpy array instead of a value.
Could you check on this?

Thanks in advance!
Eunhee

**Comment by knaidoo29** [comment]
Hi,

This seems to be an issue with concatenating arrays of arbitrary size in the latest versions of python. One way to resolve this is to go to an earlier python version 3.8 for example. This issue, if it is the one I think it is, has come up before so I'm working on a fix.

Hopefully more to follow soon.

**Comment by knaidoo29** [comment]
Hi @eunheeko , could you retry pip install mistree and see whether this error goes away. The new version of mistree should now resolve this issue.

**Comment by eunheeko** [comment]
It works perfectly. Thanks a lot!
