### ISSUE TITLE
module 'mistree' has no attribute 'GetMST'

### ISSUE THREAD

**Issue by yangfeng-Lyu** [knaidoo29/mistree#25]
Hi，knaidoo29！
I tried to load the mistree module on windows, but I encountered this problem while using it, I tried local and pip, but still no solution.

**Comment by yashreadytobox** [comment]
I am getting the same error, even after building the pure_python branch, specifically while using the pc-skeletor package [here](https://github.com/meyerls/pc-skeletor/issues/12)

**Comment by knaidoo29** [comment]
These issues should be resolved in the new version of mistree which now is completely written in python and should be installable with pip install mistree
