### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by zonca** [knaidoo29/mistree#3]
There are no tests shipping with the package.
If you refactor the code using the `astropy` package template as suggested in #2, that also gives you a predefined structure where to write and easily execute tests (with `python setup.py test`) and those are automatically executed on Travis-CI at every commit.

**Comment by knaidoo29** [comment]
Hi @zonca apologies about the delay this required a bit more work than the previous issues you raised. 

I've now added test routines to check that mistree is performing correctly. This is synced with Travis-CI and codecov. Synced badges for these are displayed in the github README.

**Comment by zonca** [comment]
very nice, tests work both with `python setup.py test` and `py.test`
![image](https://user-images.githubusercontent.com/383090/65054458-6e0d6d80-d922-11e9-97ab-ed0f27f63dad.png)

for this warning: `mistree/tests/test_plot_mst.py:67: DeprecationWarning: invalid escape sequence \c
    pmst.plot(units='$^{\circ}$', plt_output='close')`, you probably have to add `r` in front of the string.

**Comment by knaidoo29** [comment]
Hi @zonca, I've added the `r` to the string. I haven't seen this error when I've ran python setup.py test or py.test so I'm not sure if it's solved. I've tried running it with and without the `r` and the plots look the same in either case.

**Comment by zonca** [comment]
Yes it is solved, it was in the Travis logs for the old builds
