### ISSUE TITLE
Add example notebook

### ISSUE THREAD

**Issue by zonca** [knaidoo29/mistree#5]
There are good tutorials in the docs, but it would be nice to have them also in the form of a notebook or two so that users can download and start hacking on them directly instead of copy-pasting from the docs. This is just a suggestion, your choice.

**Comment by knaidoo29** [comment]
I think this is a great idea, I will work on it (maybe not as a priority) but soon.

**Comment by knaidoo29** [comment]
I have just added two ipython notebooks located here https://github.com/knaidoo29/mistree/tree/master/tutorials/notebooks which are essentially the tutorials in the documentation in a notebook version.

**Comment by zonca** [comment]
the executed versions are too big for the repo, better do "Clear all outputs" and commit only the clean version.
What I generally do, is I put the executed version in a [gist](https://gist.github.com/) and then in the documentation I link both to the clean version in the repo and the executed version.

**Comment by knaidoo29** [comment]
Ah okay, so this is why it isn't loading. Okay I will do that in the next hour.

**Comment by knaidoo29** [comment]
Okay @zonca I've added a clean version of the tutorials to the repository, and also included a binder (https://mybinder.org/v2/gh/knaidoo29/mistree/master?filepath=tutorials%2Fnotebooks%2F) link for people to play with online.

**Comment by zonca** [comment]
very good!
