### ISSUE TITLE
Improve JOSS paper

### ISSUE THREAD

**Issue by zonca** [knaidoo29/mistree#7]
- [x] Expand summary, add clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience
- [x] After you fix #4 , see if you can re-use some of that in the paper
- [x] You mention `n-point` statistics, can you look for a review paper on that you can cite?

I'll expand this in the next days but you can start working on these items.

**Comment by knaidoo29** [comment]
Hi @zonca I've replaced the summary with the introduction I provide in the README and documentation. I've also added a reference to an implementation of n-point statistics by Szapudi and Szalay (1998).

**Comment by zonca** [comment]
- [ ] in the abstract you are mentioning Kruskal’s algorithm without any link or explanation.
- [ ] you say: "...will enable the inclusion of high-order statistics information from the cosmic web", go ahread, what does this high order statistics allow you to do that wasn't doable before?

**Comment by melissawm** [comment]
I agree with the points above and will wait for this issue to close before I approve the paper. Otherwise it looks good to me.

**Comment by knaidoo29** [comment]
Hi both, apologies about the delay. I've made some changes to the paper following @zonca suggestions.

I now provide a reference for the kruskal algorithm and provide a brief explanation in the second paragraph in the motivation section.

I mention in the abstract that adding higher order statistics allows for improved constraints on cosmological parameters.

As for the target audience I've added this line at the end of the summary:

> MiSTree was designed to be used in cosmology but could be used in any field which requires extracting non-Gaussian information from point distributions.

And I've changed the typo in the spelling of facilities.

**Comment by knaidoo29** [comment]
Oh, I forgot to mention I've made some cosmetic changes to the plots included to make them look a bit better and to showcase the capabilities of the plotting routines.

**Comment by zonca** [comment]
thanks @knaidoo29, I think we are almost done, please check a few other points below:

- [ ] improve summary: the paper starts with "The minimum spanning tree (MST) has been used in a broad range of scientific fields including computer science, epidemiology, social sciences, particle physics, astronomy and cosmology", please first explain what is a minimum spanning tree is and to what kind of data is applied. Then instead of a list of disciplines, I think it would be better to just mention 2 or 3 and for each of them a simple example of an application so the reader can get an idea of the kind of problems a MST can solve
- [ ] typo:  `scipys'` -> `scipy's`
- [ ] please rephrase this, I don't understand the meaning: "It was designed to be easy to use, with the raw input data into scipys' minimum_spanning_tree function and output being handled by MiSTree itself"
- [ ] you mention this has been used in cosmology, please cite a paper about that

**Comment by knaidoo29** [comment]
Hi @zonca, I've made the changes (which is why regenerated the pdf) but I just want to look through it over the next day, so you don't need to check it just yet. I'll let you know when I'm happy with it.

**Comment by zonca** [comment]
Well done! I like the the new summary a lot.
